services:
  python-app:
    image: python:3.12-slim
    container_name: python-app
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -e . && pip install pytest pytest-cov && python -m pytest"
